add_newline = true
format = "$all"

[directory]
style = "cyan"
truncation_length = 5

[cmd_duration]
format = " took [$duration]($style)"
style = "yellow"

[package]
disabled = true

[aws]
disabled = true
style = "blue"

[git_branch]
style = "green"
symbol = "🌱 "

[git_status]
style = "yellow"

[nodejs]
style = "bright-green"

[python]
style = "bright-yellow"

[golang]
style = "cyan"

[ruby]
style = "red"
