tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "git"
brew "curl"
brew "tree"
brew "vim"

cask "font-fira-code-nerd-font"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "raycast"
cask "visual-studio-code"
# cask "slack"