brew "git"
brew "curl"
brew "tree"
brew "vim"
brew "fzf"
brew "ghq"
brew "bat"
brew "eza"
brew "sheldon"
brew "starship"
brew "mise"
brew "git-delta"

cask "font-fira-code-nerd-font"
cask "docker-desktop"
cask "google-chrome"
cask "raycast"
cask "visual-studio-code"
cask "wezterm"

# MX ERGO
cask "hammerspoon"
cask "logi-options+"