alias c='clear' # ^L
alias cdd='cd ~/Desktop'
alias dot='cd ~/dotfiles'
alias relogin='exec $SHELL -l'
alias ls="ls -1G"
alias ll="ls -lG"
alias la="ls -laG"
alias cat="bat --plain"
alias d='docker'
alias dc='docker-compose'
