alias c='clear' # ^L
alias cdd='cd ~/Desktop'
alias dot='cd ~/dotfiles'
alias relogin='exec $SHELL -l'
alias ls="eza --icons --group-directories-first"
alias ll="ls -l"
alias la="ll -a"
alias cat="bat --plain"
alias d='docker'
alias dc='docker-compose'
